
    
steps:
- label: "Just wait"
  command: "sleep 10000000"
  agents:
    queue: kubernetes
    
- label: "Kubectl version :congratulations: :champagne:"
  agents:
    queue: kubernetes
  plugins:
    - kubernetes:
        gitEnvFrom:
          - secretRef:
              name: my-git-ssh-credentials
        podSpec:
          containers:
            - image: alpine/k8s:1.27.5
              command: [kubectl]
              args:
                - "version"
                - "--short"
              resources:
                limits:
                  cpu: "100m"
                  memory: "128Mi"
